openapi: 3.0.3
info:
  title: Goa API
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for calc
paths:
  /div/{a}/{b}:
    get:
      tags:
      - calc
      summary: div calc
      operationId: calc#div
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        schema:
          type: integer
          description: Left operand
          example: 8723986392256123438
          format: int64
        example: 9092197569596372935
      - name: b
        in: path
        description: Right operand
        required: true
        schema:
          type: integer
          description: Right operand
          example: 2937026320033011362
          format: int64
        example: 207017106558923967
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 1016925590796087323
                format: int64
              example: 6001261670528037577
        "400":
          description: Bad Request response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DivByZero'
              example: Delectus quam.
components:
  schemas:
    DivByZero:
      type: string
      example: Mollitia placeat tenetur qui.
tags:
- name: calc
