// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "survey": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/goadesign/examples/form_encoding/design
// --out=$(GOPATH)/src/github.com/goadesign/examples/form_encoding
// --version=v1.3.1

package app
