// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "survey": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/goadesign/examples/form_encoding/design
// --out=$(GOPATH)/src/github.com/goadesign/examples/form_encoding
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
)

// ResultMedia media type (default view)
//
// Identifier: application/vnd.goa.example.form; view=default
type ResultMedia struct {
	// Thank you message
	Message string `form:"message" json:"message" xml:"message"`
	// Voter name
	Name string `form:"name" json:"name" xml:"name"`
}

// Validate validates the ResultMedia media type instance.
func (mt *ResultMedia) Validate() (err error) {
	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	if mt.Message == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "message"))
	}
	return
}
