swagger: "2.0"
info:
  title: Calculator Service
  description: HTTP service for adding numbers, a goa teaser
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /add:
    get:
      tags:
      - calc
      summary: add calc
      operationId: calc#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/CalcAddRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /swagger.json:
    get:
      tags:
      - calc
      summary: Download ../../gen/http/openapi.json
      operationId: calc#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      - https
definitions:
  CalcAddRequestBody:
    title: CalcAddRequestBody
    type: object
    properties:
      a:
        type: integer
        description: Left operand
        example: 8133055152903002499
        format: int64
      b:
        type: integer
        description: Right operand
        example: 3219793201326175278
        format: int64
    example:
      a: 8803302123552712831
      b: 5401762099778430809
