// Code generated by goagen v1.4.3, DO NOT EDIT.
//
// API "adder": Application User Types
//
// Command:
// $ goagen
// --design=github.com/goadesign/examples/adder/design
// --out=$(GOPATH)/src/github.com/goadesign/examples/adder
// --version=v1.4.3

package client
